config:
  # This is a test server run by team Artillery
  # It's designed to be highly scalable
  target: http://localhost:8080
  phases:
    - duration: 60
      arrivalRate: 5
scenarios:
  - flow:
      - loop:
          - get:
              url: '/actuator/test'
        count: 100