spring:
  profiles:
    default: local

  banner:
    location: static/banner/banner.txt
    charset: UTF-8
  
  output:
    ansi:
      enabled: always

  main:
    allow-bean-definition-overriding: true

  config:
    import: oauth2.yml

  redis:
    pool:
      min-idle: 0
      max-idle: 8
      max-active: 8

  jackson:
    time-zone: Asia/Seoul

logging:
  config: classpath:logging/logback-spring.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"
