# name: Build and Deploy to EC2

# on:
#   push:
#     branches:
#       - "main"

# jobs:
#   build_BE:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Set up JDK 17
#         uses: actions/setup-java@v3
#         with:
#           java-version: "17"
#           distribution: "temurin"

#       - name: Show YML Settings
#         run: echo "[INFO] YML Settings"

#       - name: Give permissions to gradlew
#         run: chmod +x gradlew

#       - name: Build backend
#         run: |
#           ./gradlew clean build -x test

#       - name: Copy JAR locally
#         run: cp build/libs/Mitchinmat_BE-0.0.1-SNAPSHOT.jar ./Mitchinmat_BE-0.0.1-SNAPSHOT.jar

#       - name: Deploy to EC2 via SSH
#         env:
#           KEY: ${{ secrets.EC2_SSH_KEY }}
#           HOST: ${{ secrets.EC2_HOST }}
#           USER: ${{ secrets.EC2_USER }}
#         run: |
#           # Save the SSH key into a file
#           echo "$KEY" > key.pem
#           chmod 400 key.pem

#           # Copy the JAR file to the EC2 instance using SCP
#           scp -i key.pem Mitchinmat_BE-0.0.1-SNAPSHOT.jar $USER@$HOST:/home/ec2-user/backend/

#           # Optionally, you can SSH into the EC2 instance and run your script to deploy the JAR
#           ssh -i key.pem $USER@$HOST 'bash ~/spring.sh'

#       - name: Clean up
#         run: rm key.pem
name: Build and Deploy to EC2

on:
  push:
    branches:
      - "main"

jobs:
  build_BE:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Show YML Settings
        run: echo "[INFO] YML Settings"

      - name: Give permissions to gradlew
        run: chmod +x gradlew

      - name: Build backend
        run: |
          ./gradlew clean build -x test
      - name: Copy JAR locally
        run: cp build/libs/Mitchinmat_BE-0.0.1-SNAPSHOT.jar ./Mitchinmat_BE-0.0.1-SNAPSHOT.jar

      - name: Deploy to EC2 via SCP
        uses: appleboy/scp-action@master
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          port: 22
          source: Mitchinmat_BE-0.0.1-SNAPSHOT.jar
          target: /home/ec2-user/backend

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          port: 22
          script: bash ~/spring.sh
